# Generated by Django 4.1.4 on 2022-12-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('0', 'web'), ('1', 'app')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('project_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio item',
                'verbose_name_plural': 'Portfolio items',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_item', to='main.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio item gallery',
                'verbose_name_plural': 'Portfolio item gallery',
                'ordering': ('name',),
            },
        ),
    ]
