# Generated by Django 4.1.4 on 2023-01-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the service', max_length=255, null=True)),
                ('image', models.CharField(blank=True, help_text="Presentation icon of the service (for example, 'bx bxl-dribbble')", max_length=255, null=True)),
                ('color', models.CharField(blank=True, choices=[('blue', 'Blue'), ('orange', 'Orange'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('red', 'Red'), ('teal', 'Teal')], default='blue', help_text="Background 'on hover' color of the service icon", max_length=255, null=True)),
                ('svg_path', models.TextField(blank=True, help_text='SVG path <d> attribute', null=True)),
                ('data_aos_delay', models.CharField(blank=True, choices=[('blue', 'Blue'), ('orange', 'Orange'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('red', 'Red'), ('teal', 'Teal')], default='blue', help_text="Background 'on hover' color of the service icon", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the service', null=True)),
            ],
            options={
                'verbose_name': 'Service item',
                'verbose_name_plural': 'Service items',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='portfolioitemgallery',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the service details slider image', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the service details slider', null=True, upload_to='services/items/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_item', to='main.serviceitem')),
            ],
            options={
                'verbose_name': 'Service item gallery',
                'verbose_name_plural': 'Service item gallery',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceItemClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the client', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, help_text='Logo image of the client', null=True, upload_to='services/clients/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to='main.serviceitem')),
            ],
            options={
                'verbose_name': 'Service item client',
                'verbose_name_plural': 'Service item clients',
                'ordering': ('name',),
            },
        ),
    ]
