# Generated by Django 4.1.4 on 2023-01-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_serviceitem_alter_portfolioitemgallery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='full_description',
            field=models.TextField(blank=True, help_text='Full description of the service. HTML tags can be used for text format', null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='data_aos_delay',
            field=models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600')], default='blue', help_text="Background 'on hover' color of the service icon", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the service. HTML tags can be used for text format', null=True),
        ),
    ]
